// Copyright © 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All Rights Reserved.
//
// This software and associated documentation files (hereinafter collectively referred to as
// "Software") is a proprietary commercial software developed by MetaX Integrated Circuits
// (Shanghai) Co., Ltd. and/or its affiliates (hereinafter collectively referred to as “MetaX”).
// The information presented in the Software belongs to MetaX. Without prior written permission
// from MetaX, no entity or individual has the right to obtain a copy of the Software to deal in
// the Software, including but not limited to use, copy, modify, merge, disclose, publish,
// distribute, sublicense, and/or sell copies of the Software or substantial portions of the Software.
//
// The Software is provided for reference only, without warranty of any kind, either express or
// implied, including but not limited to the warranty of merchantability, fitness for any purpose
// and/or noninfringement. In no case shall MetaX be liable for any claim, damage or other liability
// arising from, out of or in connection with the Software.
//
// If the Software need to be used in conjunction with any third-party software or open source
// software, the rights to the third-party software or open source software still belong to the
// copyright owners. For details, please refer to the respective notices or licenses. Please comply
// with the provisions of the relevant notices or licenses. If the open source software licenses
// additionally require the disposal of rights related to this Software, please contact MetaX
// immediately and obtain MetaX 's written consent.
//
// MetaX reserves the right, at its sole discretion, to change, modify, add or remove portions of the
// Software, at any time. MetaX reserves all the right for the final explanation.

// WARNING: This file has automatically been generated on Tue, 13 Jan 2026 17:58:51 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mxsmlextension

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "MxSmlExtension.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"sync"
	"unsafe"
)

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}
