// Copyright © 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All Rights Reserved.
//
// This software and associated documentation files (hereinafter collectively referred to as
// "Software") is a proprietary commercial software developed by MetaX Integrated Circuits
// (Shanghai) Co., Ltd. and/or its affiliates (hereinafter collectively referred to as “MetaX”).
// The information presented in the Software belongs to MetaX. Without prior written permission
// from MetaX, no entity or individual has the right to obtain a copy of the Software to deal in
// the Software, including but not limited to use, copy, modify, merge, disclose, publish,
// distribute, sublicense, and/or sell copies of the Software or substantial portions of the Software.
//
// The Software is provided for reference only, without warranty of any kind, either express or
// implied, including but not limited to the warranty of merchantability, fitness for any purpose
// and/or noninfringement. In no case shall MetaX be liable for any claim, damage or other liability
// arising from, out of or in connection with the Software.
//
// If the Software need to be used in conjunction with any third-party software or open source
// software, the rights to the third-party software or open source software still belong to the
// copyright owners. For details, please refer to the respective notices or licenses. Please comply
// with the provisions of the relevant notices or licenses. If the open source software licenses
// additionally require the disposal of rights related to this Software, please contact MetaX
// immediately and obtain MetaX 's written consent.
//
// MetaX reserves the right, at its sole discretion, to change, modify, add or remove portions of the
// Software, at any time. MetaX reserves all the right for the final explanation.

// WARNING: This file has automatically been generated on Thu, 29 Jan 2026 15:11:00 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mxsmlextension

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "MxSmlExtension.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// MXSMLEX_DBDF_ID_BUFFER_SIZE as defined in MxSmlExtension.h
	MXSMLEX_DBDF_ID_BUFFER_SIZE = 32
	// MXSMLEX_DBDF_ID_BUFFER_V2_SIZE as defined in MxSmlExtension.h
	MXSMLEX_DBDF_ID_BUFFER_V2_SIZE = 16
	// MXSMLEX_DEVICE_UUID_BUFFER_SIZE as defined in MxSmlExtension.h
	MXSMLEX_DEVICE_UUID_BUFFER_SIZE = 80
	// MXSMLEX_NAME_V2_BUFFER_SIZE as defined in MxSmlExtension.h
	MXSMLEX_NAME_V2_BUFFER_SIZE = 96
	// MXSMLEX_DRIVER_VERSION_BUFFER_SIZE as defined in MxSmlExtension.h
	MXSMLEX_DRIVER_VERSION_BUFFER_SIZE = 80
	// MXSMLEX_FI_DEV_METAXLINK_LINK_COUNT as defined in MxSmlExtension.h
	MXSMLEX_FI_DEV_METAXLINK_LINK_COUNT = 91
)

// MxSmlExReturn as declared in MxSmlExtension.h
type MxSmlExReturn int32

// MxSmlExReturn enumeration from MxSmlExtension.h
const (
	MXSMLEX_SUCCESS                         MxSmlExReturn = iota
	MXSMLEX_ERROR_UNINITIALIZED             MxSmlExReturn = 1
	MXSMLEX_ERROR_INVALID_ARGUMENT          MxSmlExReturn = 2
	MXSMLEX_ERROR_NOT_SUPPORTED             MxSmlExReturn = 3
	MXSMLEX_ERROR_NO_PERMISSION             MxSmlExReturn = 4
	MXSMLEX_ERROR_ALREADY_INITIALIZED       MxSmlExReturn = 5
	MXSMLEX_ERROR_NOT_FOUND                 MxSmlExReturn = 6
	MXSMLEX_ERROR_INSUFFICIENT_SIZE         MxSmlExReturn = 7
	MXSMLEX_ERROR_INSUFFICIENT_POWER        MxSmlExReturn = 8
	MXSMLEX_ERROR_DRIVER_NOT_LOADED         MxSmlExReturn = 9
	MXSMLEX_ERROR_TIMEOUT                   MxSmlExReturn = 10
	MXSMLEX_ERROR_IRQ_ISSUE                 MxSmlExReturn = 11
	MXSMLEX_ERROR_LIBRARY_NOT_FOUND         MxSmlExReturn = 12
	MXSMLEX_ERROR_FUNCTION_NOT_FOUND        MxSmlExReturn = 13
	MXSMLEX_ERROR_CORRUPTED_INFOROM         MxSmlExReturn = 14
	MXSMLEX_ERROR_GPU_IS_LOST               MxSmlExReturn = 15
	MXSMLEX_ERROR_RESET_REQUIRED            MxSmlExReturn = 16
	MXSMLEX_ERROR_OPERATING_SYSTEM          MxSmlExReturn = 17
	MXSMLEX_ERROR_LIB_RM_VERSION_MISMATCH   MxSmlExReturn = 18
	MXSMLEX_ERROR_IN_USE                    MxSmlExReturn = 19
	MXSMLEX_ERROR_MEMORY                    MxSmlExReturn = 20
	MXSMLEX_ERROR_NO_DATA                   MxSmlExReturn = 21
	MXSMLEX_ERROR_VGPU_ECC_NOT_SUPPORTED    MxSmlExReturn = 22
	MXSMLEX_ERROR_INSUFFICIENT_RESOURCES    MxSmlExReturn = 23
	MXSMLEX_ERROR_FREQ_NOT_SUPPORTED        MxSmlExReturn = 24
	MXSMLEX_ERROR_ARGUMENT_VERSION_MISMATCH MxSmlExReturn = 25
	MXSMLEX_ERROR_DEPRECATED                MxSmlExReturn = 26
	MXSMLEX_ERROR_UNKNOWN                   MxSmlExReturn = 999
)

// MxSmlExTemperatureSensors as declared in MxSmlExtension.h
type MxSmlExTemperatureSensors int32

// MxSmlExTemperatureSensors enumeration from MxSmlExtension.h
const (
	MXSMLEX_TEMPERATURE_GPU   MxSmlExTemperatureSensors = iota
	MXSMLEX_TEMPERATURE_COUNT MxSmlExTemperatureSensors = 1
)

// MxSmlExPcieUtilCounter as declared in MxSmlExtension.h
type MxSmlExPcieUtilCounter int32

// MxSmlExPcieUtilCounter enumeration from MxSmlExtension.h
const (
	MXSMLEX_PCIE_UTIL_TX_BYTES MxSmlExPcieUtilCounter = iota
	MXSMLEX_PCIE_UTIL_RX_BYTES MxSmlExPcieUtilCounter = 1
	MXSMLEX_PCIE_UTIL_COUNT    MxSmlExPcieUtilCounter = 2
)

// MxSmlExTemperatureThresholds as declared in MxSmlExtension.h
type MxSmlExTemperatureThresholds int32

// MxSmlExTemperatureThresholds enumeration from MxSmlExtension.h
const (
	MXSMLEX_TEMPERATURE_THRESHOLD_SHUTDOWN      MxSmlExTemperatureThresholds = iota
	MXSMLEX_TEMPERATURE_THRESHOLD_SLOWDOWN      MxSmlExTemperatureThresholds = 1
	MXSMLEX_TEMPERATURE_THRESHOLD_MEM_MAX       MxSmlExTemperatureThresholds = 2
	MXSMLEX_TEMPERATURE_THRESHOLD_GPU_MAX       MxSmlExTemperatureThresholds = 3
	MXSMLEX_TEMPERATURE_THRESHOLD_ACOUSTIC_MIN  MxSmlExTemperatureThresholds = 4
	MXSMLEX_TEMPERATURE_THRESHOLD_ACOUSTIC_CURR MxSmlExTemperatureThresholds = 5
	MXSMLEX_TEMPERATURE_THRESHOLD_ACOUSTIC_MAX  MxSmlExTemperatureThresholds = 6
	MXSMLEX_TEMPERATURE_THRESHOLD_COUNT         MxSmlExTemperatureThresholds = 7
)

// MxSmlExClockType as declared in MxSmlExtension.h
type MxSmlExClockType int32

// MxSmlExClockType enumeration from MxSmlExtension.h
const (
	MXSMLEX_CLOCK_GRAPHICS MxSmlExClockType = iota
	MXSMLEX_CLOCK_SM       MxSmlExClockType = 1
	MXSMLEX_CLOCK_MEM      MxSmlExClockType = 2
	MXSMLEX_CLOCK_VIDEO    MxSmlExClockType = 3
	MXSMLEX_CLOCK_COUNT    MxSmlExClockType = 4
)

// MxSmlExClockId as declared in MxSmlExtension.h
type MxSmlExClockId int32

// MxSmlExClockId enumeration from MxSmlExtension.h
const (
	MXSMLEX_CLOCK_ID_CURRENT            MxSmlExClockId = iota
	MXSMLEX_CLOCK_ID_APP_CLOCK_TARGET   MxSmlExClockId = 1
	MXSMLEX_CLOCK_ID_APP_CLOCK_DEFAULT  MxSmlExClockId = 2
	MXSMLEX_CLOCK_ID_CUSTOMER_BOOST_MAX MxSmlExClockId = 3
	MXSMLEX_CLOCK_ID_COUNT              MxSmlExClockId = 4
)

// MxSmlExGpuP2PStatus as declared in MxSmlExtension.h
type MxSmlExGpuP2PStatus int32

// MxSmlExGpuP2PStatus enumeration from MxSmlExtension.h
const (
	MXSMLEX_P2P_STATUS_OK                         MxSmlExGpuP2PStatus = iota
	MXSMLEX_P2P_STATUS_CHIPSET_NOT_SUPPORTED      MxSmlExGpuP2PStatus = 1
	MXSMLEX_P2P_STATUS_GPU_NOT_SUPPORTED          MxSmlExGpuP2PStatus = 2
	MXSMLEX_P2P_STATUS_IOH_TOPOLOGY_NOT_SUPPORTED MxSmlExGpuP2PStatus = 3
	MXSMLEX_P2P_STATUS_DISABLED_BY_REGKEY         MxSmlExGpuP2PStatus = 4
	MXSMLEX_P2P_STATUS_NOT_SUPPORTED              MxSmlExGpuP2PStatus = 5
	MXSMLEX_P2P_STATUS_UNKNOWN                    MxSmlExGpuP2PStatus = 6
)

// MxSmlExGpuP2PCapsIndex as declared in MxSmlExtension.h
type MxSmlExGpuP2PCapsIndex int32

// MxSmlExGpuP2PCapsIndex enumeration from MxSmlExtension.h
const (
	MXSMLEX_P2P_CAPS_INDEX_READ    MxSmlExGpuP2PCapsIndex = iota
	MXSMLEX_P2P_CAPS_INDEX_WRITE   MxSmlExGpuP2PCapsIndex = 1
	MXSMLEX_P2P_CAPS_INDEX_MXLINK  MxSmlExGpuP2PCapsIndex = 2
	MXSMLEX_P2P_CAPS_INDEX_ATOMICS MxSmlExGpuP2PCapsIndex = 3
	MXSMLEX_P2P_CAPS_INDEX_PROP    MxSmlExGpuP2PCapsIndex = 4
	MXSMLEX_P2P_CAPS_INDEX_UNKNOWN MxSmlExGpuP2PCapsIndex = 5
)

// MxSmlExPstates as declared in MxSmlExtension.h
type MxSmlExPstates int32

// MxSmlExPstates enumeration from MxSmlExtension.h
const (
	MXSMLEX_PSTATE_0       MxSmlExPstates = iota
	MXSMLEX_PSTATE_1       MxSmlExPstates = 1
	MXSMLEX_PSTATE_2       MxSmlExPstates = 2
	MXSMLEX_PSTATE_3       MxSmlExPstates = 3
	MXSMLEX_PSTATE_4       MxSmlExPstates = 4
	MXSMLEX_PSTATE_5       MxSmlExPstates = 5
	MXSMLEX_PSTATE_6       MxSmlExPstates = 6
	MXSMLEX_PSTATE_7       MxSmlExPstates = 7
	MXSMLEX_PSTATE_8       MxSmlExPstates = 8
	MXSMLEX_PSTATE_9       MxSmlExPstates = 9
	MXSMLEX_PSTATE_10      MxSmlExPstates = 10
	MXSMLEX_PSTATE_11      MxSmlExPstates = 11
	MXSMLEX_PSTATE_12      MxSmlExPstates = 12
	MXSMLEX_PSTATE_13      MxSmlExPstates = 13
	MXSMLEX_PSTATE_14      MxSmlExPstates = 14
	MXSMLEX_PSTATE_15      MxSmlExPstates = 15
	MXSMLEX_PSTATE_UNKNOWN MxSmlExPstates = 32
)

// MxSmlExEnableState as declared in MxSmlExtension.h
type MxSmlExEnableState int32

// MxSmlExEnableState enumeration from MxSmlExtension.h
const (
	MXSMLEX_FEATURE_DISABLED MxSmlExEnableState = iota
	MXSMLEX_FEATURE_ENABLED  MxSmlExEnableState = 1
)

// MxSmlExGpuTopologyLevel as declared in MxSmlExtension.h
type MxSmlExGpuTopologyLevel int32

// MxSmlExGpuTopologyLevel enumeration from MxSmlExtension.h
const (
	MXSMLEX_TOPOLOGY_INTERNAL   MxSmlExGpuTopologyLevel = iota
	MXSMLEX_TOPOLOGY_SINGLE     MxSmlExGpuTopologyLevel = 10
	MXSMLEX_TOPOLOGY_MULTIPLE   MxSmlExGpuTopologyLevel = 20
	MXSMLEX_TOPOLOGY_HOSTBRIDGE MxSmlExGpuTopologyLevel = 30
	MXSMLEX_TOPOLOGY_NODE       MxSmlExGpuTopologyLevel = 40
	MXSMLEX_TOPOLOGY_SYSTEM     MxSmlExGpuTopologyLevel = 50
)

// MxSmlExMetaXLinkDeviceType as declared in MxSmlExtension.h
type MxSmlExMetaXLinkDeviceType int32

// MxSmlExMetaXLinkDeviceType enumeration from MxSmlExtension.h
const (
	MXSMLEX_METAXLINK_DEVICE_TYPE_GPU     MxSmlExMetaXLinkDeviceType = iota
	MXSMLEX_METAXLINK_DEVICE_TYPE_NPU     MxSmlExMetaXLinkDeviceType = 1
	MXSMLEX_METAXLINK_DEVICE_TYPE_SWITCH  MxSmlExMetaXLinkDeviceType = 2
	MXSMLEX_METAXLINK_DEVICE_TYPE_UNKNOWN MxSmlExMetaXLinkDeviceType = 255
)

// MxSmlExValueType as declared in MxSmlExtension.h
type MxSmlExValueType int32

// MxSmlExValueType enumeration from MxSmlExtension.h
const (
	MXSMLEX_VALUE_TYPE_DOUBLE             MxSmlExValueType = iota
	MXSMLEX_VALUE_TYPE_UNSIGNED_INT       MxSmlExValueType = 1
	MXSMLEX_VALUE_TYPE_UNSIGNED_LONG      MxSmlExValueType = 2
	MXSMLEX_VALUE_TYPE_UNSIGNED_LONG_LONG MxSmlExValueType = 3
	MXSMLEX_VALUE_TYPE_SIGNED_LONG_LONG   MxSmlExValueType = 4
	MXSMLEX_VALUE_TYPE_SIGNED_INT         MxSmlExValueType = 5
	MXSMLEX_VALUE_TYPE_COUNT              MxSmlExValueType = 6
)
