// Copyright © 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All Rights Reserved.
//
// This software and associated documentation files (hereinafter collectively referred to as
// "Software") is a proprietary commercial software developed by MetaX Integrated Circuits
// (Shanghai) Co., Ltd. and/or its affiliates (hereinafter collectively referred to as “MetaX”).
// The information presented in the Software belongs to MetaX. Without prior written permission
// from MetaX, no entity or individual has the right to obtain a copy of the Software to deal in
// the Software, including but not limited to use, copy, modify, merge, disclose, publish,
// distribute, sublicense, and/or sell copies of the Software or substantial portions of the Software.
//
// The Software is provided for reference only, without warranty of any kind, either express or
// implied, including but not limited to the warranty of merchantability, fitness for any purpose
// and/or noninfringement. In no case shall MetaX be liable for any claim, damage or other liability
// arising from, out of or in connection with the Software.
//
// If the Software need to be used in conjunction with any third-party software or open source
// software, the rights to the third-party software or open source software still belong to the
// copyright owners. For details, please refer to the respective notices or licenses. Please comply
// with the provisions of the relevant notices or licenses. If the open source software licenses
// additionally require the disposal of rights related to this Software, please contact MetaX
// immediately and obtain MetaX 's written consent.
//
// MetaX reserves the right, at its sole discretion, to change, modify, add or remove portions of the
// Software, at any time. MetaX reserves all the right for the final explanation.

// WARNING: This file has automatically been generated on Thu, 29 Jan 2026 15:11:00 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mxsmlextension

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "MxSmlExtension.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// mxSmlExInit function as declared in MxSmlExtension.h
func mxSmlExInit() MxSmlExReturn {
	__ret := C.mxSmlExInit()
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExGetDeviceHandleByIndex function as declared in MxSmlExtension.h
func mxSmlExGetDeviceHandleByIndex(DeviceId uint32, DeviceHandle *MxSmlExDevice) MxSmlExReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDeviceHandle, cDeviceHandleAllocMap := (*C.mxSmlExDevice_t)(unsafe.Pointer(DeviceHandle)), cgoAllocsUnknown
	__ret := C.mxSmlExGetDeviceHandleByIndex(cDeviceId, cDeviceHandle)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExGetDeviceHandleByPciBusId function as declared in MxSmlExtension.h
func mxSmlExGetDeviceHandleByPciBusId(PciBusId string, DeviceHandle *MxSmlExDevice) MxSmlExReturn {
	cPciBusId, cPciBusIdAllocMap := unpackPCharString(PciBusId)
	cDeviceHandle, cDeviceHandleAllocMap := (*C.mxSmlExDevice_t)(unsafe.Pointer(DeviceHandle)), cgoAllocsUnknown
	__ret := C.mxSmlExGetDeviceHandleByPciBusId(cPciBusId, cDeviceHandle)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	runtime.KeepAlive(cPciBusIdAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetPciInfo function as declared in MxSmlExtension.h
func mxSmlExDeviceGetPciInfo(DeviceHandle MxSmlExDevice, Pci *MxSmlExPciInfo) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cPci, cPciAllocMap := (*C.mxSmlExPciInfo_t)(unsafe.Pointer(Pci)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetPciInfo(cDeviceHandle, cPci)
	runtime.KeepAlive(cPciAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetFanSpeed function as declared in MxSmlExtension.h
func mxSmlExDeviceGetFanSpeed(DeviceHandle MxSmlExDevice, Speed *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (*C.uint)(unsafe.Pointer(Speed)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetFanSpeed(cDeviceHandle, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetFanSpeed_v2 function as declared in MxSmlExtension.h
func mxSmlExDeviceGetFanSpeed_v2(DeviceHandle MxSmlExDevice, Fan uint32, Speed *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cFan, cFanAllocMap := (C.uint)(Fan), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (*C.uint)(unsafe.Pointer(Speed)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetFanSpeed_v2(cDeviceHandle, cFan, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cFanAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetUtilization function as declared in MxSmlExtension.h
func mxSmlExDeviceGetUtilization(DeviceHandle MxSmlExDevice, Utilizaition *MxSmlExUtilization) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cUtilizaition, cUtilizaitionAllocMap := (*C.mxSmlExUtilization_t)(unsafe.Pointer(Utilizaition)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetUtilization(cDeviceHandle, cUtilizaition)
	runtime.KeepAlive(cUtilizaitionAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetName function as declared in MxSmlExtension.h
func mxSmlExDeviceGetName(DeviceHandle MxSmlExDevice, Name *byte, Length uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLength, cLengthAllocMap := (C.uint)(Length), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetName(cDeviceHandle, cName, cLength)
	runtime.KeepAlive(cLengthAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExSystemGetDriverVersion function as declared in MxSmlExtension.h
func mxSmlExSystemGetDriverVersion(Version *byte, Length uint32) MxSmlExReturn {
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cLength, cLengthAllocMap := (C.uint)(Length), cgoAllocsUnknown
	__ret := C.mxSmlExSystemGetDriverVersion(cVersion, cLength)
	runtime.KeepAlive(cLengthAllocMap)
	runtime.KeepAlive(cVersionAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExSystemGetMxsmlVersion function as declared in MxSmlExtension.h
func mxSmlExSystemGetMxsmlVersion(Version *byte, Length uint32) MxSmlExReturn {
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cLength, cLengthAllocMap := (C.uint)(Length), cgoAllocsUnknown
	__ret := C.mxSmlExSystemGetMxsmlVersion(cVersion, cLength)
	runtime.KeepAlive(cLengthAllocMap)
	runtime.KeepAlive(cVersionAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetMinorNumber function as declared in MxSmlExtension.h
func mxSmlExDeviceGetMinorNumber(DeviceHandle MxSmlExDevice, MinorNumber *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cMinorNumber, cMinorNumberAllocMap := (*C.uint)(unsafe.Pointer(MinorNumber)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetMinorNumber(cDeviceHandle, cMinorNumber)
	runtime.KeepAlive(cMinorNumberAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetMetaXLinkState function as declared in MxSmlExtension.h
func mxSmlExDeviceGetMetaXLinkState(DeviceHandle MxSmlExDevice, Link uint32, IsActive *MxSmlExEnableState) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cLink, cLinkAllocMap := (C.uint)(Link), cgoAllocsUnknown
	cIsActive, cIsActiveAllocMap := (*C.mxSmlExEnableState_t)(unsafe.Pointer(IsActive)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetMetaXLinkState(cDeviceHandle, cLink, cIsActive)
	runtime.KeepAlive(cIsActiveAllocMap)
	runtime.KeepAlive(cLinkAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetMetaXLinkRemotePciInfo_v2 function as declared in MxSmlExtension.h
func mxSmlExDeviceGetMetaXLinkRemotePciInfo_v2(DeviceHandle MxSmlExDevice, Link uint32, Pci *MxSmlExPciInfo) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cLink, cLinkAllocMap := (C.uint)(Link), cgoAllocsUnknown
	cPci, cPciAllocMap := (*C.mxSmlExPciInfo_t)(unsafe.Pointer(Pci)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetMetaXLinkRemotePciInfo_v2(cDeviceHandle, cLink, cPci)
	runtime.KeepAlive(cPciAllocMap)
	runtime.KeepAlive(cLinkAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExErrorString function as declared in MxSmlExtension.h
func mxSmlExErrorString(Result MxSmlExReturn) *byte {
	cResult, cResultAllocMap := (C.mxSmlExReturn_t)(Result), cgoAllocsUnknown
	__ret := C.mxSmlExErrorString(cResult)
	runtime.KeepAlive(cResultAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// mxSmlExShutdown function as declared in MxSmlExtension.h
func mxSmlExShutdown() MxSmlExReturn {
	__ret := C.mxSmlExShutdown()
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetTemperature function as declared in MxSmlExtension.h
func mxSmlExDeviceGetTemperature(DeviceHandle MxSmlExDevice, SensorType MxSmlExTemperatureSensors, Temperature *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cSensorType, cSensorTypeAllocMap := (C.mxSmlExTemperatureSensors_t)(SensorType), cgoAllocsUnknown
	cTemperature, cTemperatureAllocMap := (*C.uint)(unsafe.Pointer(Temperature)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetTemperature(cDeviceHandle, cSensorType, cTemperature)
	runtime.KeepAlive(cTemperatureAllocMap)
	runtime.KeepAlive(cSensorTypeAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetCount function as declared in MxSmlExtension.h
func mxSmlExDeviceGetCount(DeviceCount *uint32) MxSmlExReturn {
	cDeviceCount, cDeviceCountAllocMap := (*C.uint)(unsafe.Pointer(DeviceCount)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetCount(cDeviceCount)
	runtime.KeepAlive(cDeviceCountAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExMacaDeviceGetCount function as declared in MxSmlExtension.h
func mxSmlExMacaDeviceGetCount(DeviceCount *uint32) MxSmlExReturn {
	cDeviceCount, cDeviceCountAllocMap := (*C.uint)(unsafe.Pointer(DeviceCount)), cgoAllocsUnknown
	__ret := C.mxSmlExMacaDeviceGetCount(cDeviceCount)
	runtime.KeepAlive(cDeviceCountAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetCurrPcieLinkWidth function as declared in MxSmlExtension.h
func mxSmlExDeviceGetCurrPcieLinkWidth(DeviceHandle MxSmlExDevice, CurrLinkWidth *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cCurrLinkWidth, cCurrLinkWidthAllocMap := (*C.uint)(unsafe.Pointer(CurrLinkWidth)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetCurrPcieLinkWidth(cDeviceHandle, cCurrLinkWidth)
	runtime.KeepAlive(cCurrLinkWidthAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetComputeRunningProcesses function as declared in MxSmlExtension.h
func mxSmlExDeviceGetComputeRunningProcesses(DeviceHandle MxSmlExDevice, InfoCount *uint32, Infos *MxSmlExProcessInfo) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cInfoCount, cInfoCountAllocMap := (*C.uint)(unsafe.Pointer(InfoCount)), cgoAllocsUnknown
	cInfos, cInfosAllocMap := (*C.mxSmlExProcessInfo_t)(unsafe.Pointer(Infos)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetComputeRunningProcesses(cDeviceHandle, cInfoCount, cInfos)
	runtime.KeepAlive(cInfosAllocMap)
	runtime.KeepAlive(cInfoCountAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetMemoryInfo function as declared in MxSmlExtension.h
func mxSmlExDeviceGetMemoryInfo(DeviceHandle MxSmlExDevice, Memory *MxSmlExMemory) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cMemory, cMemoryAllocMap := (*C.mxSmlExMemory_t)(unsafe.Pointer(Memory)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetMemoryInfo(cDeviceHandle, cMemory)
	runtime.KeepAlive(cMemoryAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetComputeCapability function as declared in MxSmlExtension.h
func mxSmlExDeviceGetComputeCapability(DeviceHandle MxSmlExDevice, Major *int32, Minor *int32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cMajor, cMajorAllocMap := (*C.int)(unsafe.Pointer(Major)), cgoAllocsUnknown
	cMinor, cMinorAllocMap := (*C.int)(unsafe.Pointer(Minor)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetComputeCapability(cDeviceHandle, cMajor, cMinor)
	runtime.KeepAlive(cMinorAllocMap)
	runtime.KeepAlive(cMajorAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExGetPowerUsage function as declared in MxSmlExtension.h
func mxSmlExGetPowerUsage(DeviceHandle MxSmlExDevice, PowerUsage *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cPowerUsage, cPowerUsageAllocMap := (*C.uint)(unsafe.Pointer(PowerUsage)), cgoAllocsUnknown
	__ret := C.mxSmlExGetPowerUsage(cDeviceHandle, cPowerUsage)
	runtime.KeepAlive(cPowerUsageAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExGetPowerManagementLimit function as declared in MxSmlExtension.h
func mxSmlExGetPowerManagementLimit(DeviceHandle MxSmlExDevice, Limit *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cLimit, cLimitAllocMap := (*C.uint)(unsafe.Pointer(Limit)), cgoAllocsUnknown
	__ret := C.mxSmlExGetPowerManagementLimit(cDeviceHandle, cLimit)
	runtime.KeepAlive(cLimitAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExGetMaxPcieLinkWidth function as declared in MxSmlExtension.h
func mxSmlExGetMaxPcieLinkWidth(DeviceHandle MxSmlExDevice, MaxLinkWidth *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cMaxLinkWidth, cMaxLinkWidthAllocMap := (*C.uint)(unsafe.Pointer(MaxLinkWidth)), cgoAllocsUnknown
	__ret := C.mxSmlExGetMaxPcieLinkWidth(cDeviceHandle, cMaxLinkWidth)
	runtime.KeepAlive(cMaxLinkWidthAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExGetPcieThroughput function as declared in MxSmlExtension.h
func mxSmlExGetPcieThroughput(DeviceHandle MxSmlExDevice, Counter MxSmlExPcieUtilCounter, Value *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cCounter, cCounterAllocMap := (C.mxSmlExPcieUtilCounter_t)(Counter), cgoAllocsUnknown
	cValue, cValueAllocMap := (*C.uint)(unsafe.Pointer(Value)), cgoAllocsUnknown
	__ret := C.mxSmlExGetPcieThroughput(cDeviceHandle, cCounter, cValue)
	runtime.KeepAlive(cValueAllocMap)
	runtime.KeepAlive(cCounterAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetTemperatureThreshold function as declared in MxSmlExtension.h
func mxSmlExDeviceGetTemperatureThreshold(DeviceHandle MxSmlExDevice, ThresholdType MxSmlExTemperatureThresholds, Temperature *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cThresholdType, cThresholdTypeAllocMap := (C.mxSmlExTemperatureThresholds_t)(ThresholdType), cgoAllocsUnknown
	cTemperature, cTemperatureAllocMap := (*C.uint)(unsafe.Pointer(Temperature)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetTemperatureThreshold(cDeviceHandle, cThresholdType, cTemperature)
	runtime.KeepAlive(cTemperatureAllocMap)
	runtime.KeepAlive(cThresholdTypeAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetClockInfo function as declared in MxSmlExtension.h
func mxSmlExDeviceGetClockInfo(DeviceHandle MxSmlExDevice, ClockType MxSmlExClockType, Clock *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cClockType, cClockTypeAllocMap := (C.mxSmlExClockType_t)(ClockType), cgoAllocsUnknown
	cClock, cClockAllocMap := (*C.uint)(unsafe.Pointer(Clock)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetClockInfo(cDeviceHandle, cClockType, cClock)
	runtime.KeepAlive(cClockAllocMap)
	runtime.KeepAlive(cClockTypeAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetClock function as declared in MxSmlExtension.h
func mxSmlExDeviceGetClock(DeviceHandle MxSmlExDevice, ClockType MxSmlExClockType, ClockId MxSmlExClockId, Clock *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cClockType, cClockTypeAllocMap := (C.mxSmlExClockType_t)(ClockType), cgoAllocsUnknown
	cClockId, cClockIdAllocMap := (C.mxSmlExClockId_t)(ClockId), cgoAllocsUnknown
	cClock, cClockAllocMap := (*C.uint)(unsafe.Pointer(Clock)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetClock(cDeviceHandle, cClockType, cClockId, cClock)
	runtime.KeepAlive(cClockAllocMap)
	runtime.KeepAlive(cClockIdAllocMap)
	runtime.KeepAlive(cClockTypeAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetEnforcedPowerLimit function as declared in MxSmlExtension.h
func mxSmlExDeviceGetEnforcedPowerLimit(DeviceHandle MxSmlExDevice, Limit *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cLimit, cLimitAllocMap := (*C.uint)(unsafe.Pointer(Limit)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetEnforcedPowerLimit(cDeviceHandle, cLimit)
	runtime.KeepAlive(cLimitAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetCurrentClocksThrottleReasons function as declared in MxSmlExtension.h
func mxSmlExDeviceGetCurrentClocksThrottleReasons(DeviceHandle MxSmlExDevice, ClocksThrottleReasons *uint64) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cClocksThrottleReasons, cClocksThrottleReasonsAllocMap := (*C.ulonglong)(unsafe.Pointer(ClocksThrottleReasons)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetCurrentClocksThrottleReasons(cDeviceHandle, cClocksThrottleReasons)
	runtime.KeepAlive(cClocksThrottleReasonsAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetSupportedClocksThrottleReasons function as declared in MxSmlExtension.h
func mxSmlExDeviceGetSupportedClocksThrottleReasons(DeviceHandle MxSmlExDevice, SupportedClocksThrottleReasons *uint64) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cSupportedClocksThrottleReasons, cSupportedClocksThrottleReasonsAllocMap := (*C.ulonglong)(unsafe.Pointer(SupportedClocksThrottleReasons)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetSupportedClocksThrottleReasons(cDeviceHandle, cSupportedClocksThrottleReasons)
	runtime.KeepAlive(cSupportedClocksThrottleReasonsAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetCpuAffinity function as declared in MxSmlExtension.h
func mxSmlExDeviceGetCpuAffinity(DeviceHandle MxSmlExDevice, CpuSetSize uint32, CpuSet *uint64) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cCpuSetSize, cCpuSetSizeAllocMap := (C.uint)(CpuSetSize), cgoAllocsUnknown
	cCpuSet, cCpuSetAllocMap := (*C.ulong)(unsafe.Pointer(CpuSet)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetCpuAffinity(cDeviceHandle, cCpuSetSize, cCpuSet)
	runtime.KeepAlive(cCpuSetAllocMap)
	runtime.KeepAlive(cCpuSetSizeAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetSupportedMemoryClocks function as declared in MxSmlExtension.h
func mxSmlExDeviceGetSupportedMemoryClocks(DeviceHandle MxSmlExDevice, Count *uint32, ClocksMHz *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cCount, cCountAllocMap := (*C.uint)(unsafe.Pointer(Count)), cgoAllocsUnknown
	cClocksMHz, cClocksMHzAllocMap := (*C.uint)(unsafe.Pointer(ClocksMHz)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetSupportedMemoryClocks(cDeviceHandle, cCount, cClocksMHz)
	runtime.KeepAlive(cClocksMHzAllocMap)
	runtime.KeepAlive(cCountAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetSupportedGraphicsClocks function as declared in MxSmlExtension.h
func mxSmlExDeviceGetSupportedGraphicsClocks(DeviceHandle MxSmlExDevice, Count *uint32, ClocksMHz *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cCount, cCountAllocMap := (*C.uint)(unsafe.Pointer(Count)), cgoAllocsUnknown
	cClocksMHz, cClocksMHzAllocMap := (*C.uint)(unsafe.Pointer(ClocksMHz)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetSupportedGraphicsClocks(cDeviceHandle, cCount, cClocksMHz)
	runtime.KeepAlive(cClocksMHzAllocMap)
	runtime.KeepAlive(cCountAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetSupportedGraphicsClocks_v2 function as declared in MxSmlExtension.h
func mxSmlExDeviceGetSupportedGraphicsClocks_v2(DeviceHandle MxSmlExDevice, MemoryClockMHz uint32, Count *uint32, ClocksMHz *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cMemoryClockMHz, cMemoryClockMHzAllocMap := (C.uint)(MemoryClockMHz), cgoAllocsUnknown
	cCount, cCountAllocMap := (*C.uint)(unsafe.Pointer(Count)), cgoAllocsUnknown
	cClocksMHz, cClocksMHzAllocMap := (*C.uint)(unsafe.Pointer(ClocksMHz)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetSupportedGraphicsClocks_v2(cDeviceHandle, cMemoryClockMHz, cCount, cClocksMHz)
	runtime.KeepAlive(cClocksMHzAllocMap)
	runtime.KeepAlive(cCountAllocMap)
	runtime.KeepAlive(cMemoryClockMHzAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceSetApplicationsClocks function as declared in MxSmlExtension.h
func mxSmlExDeviceSetApplicationsClocks(DeviceHandle MxSmlExDevice, MemoryClockMHz uint32, GraphicsClockMHz uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cMemoryClockMHz, cMemoryClockMHzAllocMap := (C.uint)(MemoryClockMHz), cgoAllocsUnknown
	cGraphicsClockMHz, cGraphicsClockMHzAllocMap := (C.uint)(GraphicsClockMHz), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceSetApplicationsClocks(cDeviceHandle, cMemoryClockMHz, cGraphicsClockMHz)
	runtime.KeepAlive(cGraphicsClockMHzAllocMap)
	runtime.KeepAlive(cMemoryClockMHzAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceResetApplicationsClocks function as declared in MxSmlExtension.h
func mxSmlExDeviceResetApplicationsClocks(DeviceHandle MxSmlExDevice) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceResetApplicationsClocks(cDeviceHandle)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetApplicationsClock function as declared in MxSmlExtension.h
func mxSmlExDeviceGetApplicationsClock(DeviceHandle MxSmlExDevice, ClockType MxSmlExClockType, ClockMHz *uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cClockType, cClockTypeAllocMap := (C.mxSmlExClockType_t)(ClockType), cgoAllocsUnknown
	cClockMHz, cClockMHzAllocMap := (*C.uint)(unsafe.Pointer(ClockMHz)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetApplicationsClock(cDeviceHandle, cClockType, cClockMHz)
	runtime.KeepAlive(cClockMHzAllocMap)
	runtime.KeepAlive(cClockTypeAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetP2PStatus function as declared in MxSmlExtension.h
func mxSmlExDeviceGetP2PStatus(DeviceHandle1 MxSmlExDevice, DeviceHandle2 MxSmlExDevice, P2pIndex MxSmlExGpuP2PCapsIndex, P2pStatus *MxSmlExGpuP2PStatus) MxSmlExReturn {
	cDeviceHandle1, cDeviceHandle1AllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle1)), cgoAllocsUnknown
	cDeviceHandle2, cDeviceHandle2AllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle2)), cgoAllocsUnknown
	cP2pIndex, cP2pIndexAllocMap := (C.mxSmlExGpuP2PCapsIndex_t)(P2pIndex), cgoAllocsUnknown
	cP2pStatus, cP2pStatusAllocMap := (*C.mxSmlExGpuP2PStatus_t)(unsafe.Pointer(P2pStatus)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetP2PStatus(cDeviceHandle1, cDeviceHandle2, cP2pIndex, cP2pStatus)
	runtime.KeepAlive(cP2pStatusAllocMap)
	runtime.KeepAlive(cP2pIndexAllocMap)
	runtime.KeepAlive(cDeviceHandle2AllocMap)
	runtime.KeepAlive(cDeviceHandle1AllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetUUID function as declared in MxSmlExtension.h
func mxSmlExDeviceGetUUID(DeviceHandle MxSmlExDevice, Uuid *byte, Length uint32) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cUuid, cUuidAllocMap := (*C.char)(unsafe.Pointer(Uuid)), cgoAllocsUnknown
	cLength, cLengthAllocMap := (C.uint)(Length), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetUUID(cDeviceHandle, cUuid, cLength)
	runtime.KeepAlive(cLengthAllocMap)
	runtime.KeepAlive(cUuidAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetHandleByUUID function as declared in MxSmlExtension.h
func mxSmlExDeviceGetHandleByUUID(Uuid *byte, DeviceHandle *MxSmlExDevice) MxSmlExReturn {
	cUuid, cUuidAllocMap := (*C.char)(unsafe.Pointer(Uuid)), cgoAllocsUnknown
	cDeviceHandle, cDeviceHandleAllocMap := (*C.mxSmlExDevice_t)(unsafe.Pointer(DeviceHandle)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetHandleByUUID(cUuid, cDeviceHandle)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	runtime.KeepAlive(cUuidAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetPerformanceState function as declared in MxSmlExtension.h
func mxSmlExDeviceGetPerformanceState(DeviceHandle MxSmlExDevice, PState *MxSmlExPstates) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cPState, cPStateAllocMap := (*C.mxSmlExPstates_t)(unsafe.Pointer(PState)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetPerformanceState(cDeviceHandle, cPState)
	runtime.KeepAlive(cPStateAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceSetAutoBoostedClocksEnabled function as declared in MxSmlExtension.h
func mxSmlExDeviceSetAutoBoostedClocksEnabled(DeviceHandle MxSmlExDevice, Enabled MxSmlExEnableState) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cEnabled, cEnabledAllocMap := (C.mxSmlExEnableState_t)(Enabled), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceSetAutoBoostedClocksEnabled(cDeviceHandle, cEnabled)
	runtime.KeepAlive(cEnabledAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetAutoBoostedClocksEnabled function as declared in MxSmlExtension.h
func mxSmlExDeviceGetAutoBoostedClocksEnabled(DeviceHandle MxSmlExDevice, IsEnabled *MxSmlExEnableState, DefaultIsEnabled *MxSmlExEnableState) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cIsEnabled, cIsEnabledAllocMap := (*C.mxSmlExEnableState_t)(unsafe.Pointer(IsEnabled)), cgoAllocsUnknown
	cDefaultIsEnabled, cDefaultIsEnabledAllocMap := (*C.mxSmlExEnableState_t)(unsafe.Pointer(DefaultIsEnabled)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetAutoBoostedClocksEnabled(cDeviceHandle, cIsEnabled, cDefaultIsEnabled)
	runtime.KeepAlive(cDefaultIsEnabledAllocMap)
	runtime.KeepAlive(cIsEnabledAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetTopologyCommonAncestor function as declared in MxSmlExtension.h
func mxSmlExDeviceGetTopologyCommonAncestor(DeviceHandle1 MxSmlExDevice, DeviceHandle2 MxSmlExDevice, PathInfo *MxSmlExGpuTopologyLevel) MxSmlExReturn {
	cDeviceHandle1, cDeviceHandle1AllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle1)), cgoAllocsUnknown
	cDeviceHandle2, cDeviceHandle2AllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle2)), cgoAllocsUnknown
	cPathInfo, cPathInfoAllocMap := (*C.mxSmlExGpuTopologyLevel_t)(unsafe.Pointer(PathInfo)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetTopologyCommonAncestor(cDeviceHandle1, cDeviceHandle2, cPathInfo)
	runtime.KeepAlive(cPathInfoAllocMap)
	runtime.KeepAlive(cDeviceHandle2AllocMap)
	runtime.KeepAlive(cDeviceHandle1AllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetMetaXLinkRemoteDeviceType function as declared in MxSmlExtension.h
func mxSmlExDeviceGetMetaXLinkRemoteDeviceType(DeviceHandle MxSmlExDevice, Link uint32, _type *MxSmlExMetaXLinkDeviceType) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cLink, cLinkAllocMap := (C.uint)(Link), cgoAllocsUnknown
	c_type, c_typeAllocMap := (*C.mxSmlExMetaXLinkDeviceType_t)(unsafe.Pointer(_type)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetMetaXLinkRemoteDeviceType(cDeviceHandle, cLink, c_type)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cLinkAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceGetFieldValues function as declared in MxSmlExtension.h
func mxSmlExDeviceGetFieldValues(DeviceHandle MxSmlExDevice, ValuesCount int32, Values *MxSmlExFieldValue) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	cValuesCount, cValuesCountAllocMap := (C.int)(ValuesCount), cgoAllocsUnknown
	cValues, cValuesAllocMap := (*C.mxSmlExFieldValue_t)(unsafe.Pointer(Values)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceGetFieldValues(cDeviceHandle, cValuesCount, cValues)
	runtime.KeepAlive(cValuesAllocMap)
	runtime.KeepAlive(cValuesCountAllocMap)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}

// mxSmlExDeviceSetCpuAffinity function as declared in MxSmlExtension.h
func mxSmlExDeviceSetCpuAffinity(DeviceHandle MxSmlExDevice) MxSmlExReturn {
	cDeviceHandle, cDeviceHandleAllocMap := *(*C.mxSmlExDevice_t)(unsafe.Pointer(&DeviceHandle)), cgoAllocsUnknown
	__ret := C.mxSmlExDeviceSetCpuAffinity(cDeviceHandle)
	runtime.KeepAlive(cDeviceHandleAllocMap)
	__v := (MxSmlExReturn)(__ret)
	return __v
}
