// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package mxsmlextension

import "unsafe"

type MxSmlExPciInfo struct {
	BusIdLegacy    [16]int8
	Domain         uint32
	Bus            uint32
	Device         uint32
	PciDeviceId    uint32
	PciSubSystemId uint32
	BusId          [32]int8
}

type MxSmlExUtilization struct {
	Gpu    uint32
	Memory uint32
}

type MxSmlExProcessInfo struct {
	ComputeInstanceId uint32
	GpuInstanceId     uint32
	Pid               uint32
	UsedGpuMemory     uint64
}

type MxSmlExMemory struct {
	Free  uint64
	Total uint64
	Used  uint64
}

type MxSmlExDevice struct {
	Handle *_Ctype_struct_MxSmlExDevice
}

type MxSmlExExcludedDeviceInfo struct {
	PciInfo MxSmlExPciInfo
	Uuid    [80]int8
}

const sizeofMxSmlExValue = unsafe.Sizeof([8]byte{})

type MxSmlExValue [sizeofMxSmlExValue]byte

type MxSmlExFieldValue struct {
	FieldId       uint32
	LatencyUsec   int64
	MxSmlExReturn uint32
	ScopeId       uint32
	Timestamp     int64
	Value         [8]byte
	ValueType     uint32
	Pad_cgo_0     [4]byte
}

type MxSmlExSample struct {
	TimeStamp   uint64
	SampleValue [8]byte
}
